In [1]:
import numpy as np
import pickle 

In [3]:
fp = open("./dataset/train10.pkl", "rb")
data = pickle.load(fp)

In [7]:
data["node_type"][0]

array([[3],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int32)

In [9]:
unique, counts = np.unique(data["node_type"][0], return_counts = True)

In [10]:
unique

array([0, 3], dtype=int32)

In [11]:
counts

array([1577,    2])

In [13]:
fpt = open("./dataset/test10.pkl", "rb")
data_test = pickle.load(fp)

In [15]:
data_test.keys()

dict_keys(['cells', 'mesh_pos', 'node_type', 'world_pos', 'prev|world_pos', 'target|world_pos'])

In [16]:
data_test["cells"].shape

(399, 3028, 3)

In [23]:
import numpy as np
np.sum(np.equal(data["cells"][0] , data["cells"][1]))

9084

In [24]:
3028 * 3

9084

In [25]:
data.keys()

dict_keys(['cells', 'mesh_pos', 'node_type', 'world_pos', 'prev|world_pos', 'target|world_pos'])